joint_limits:
  arm_joint_1_yaw:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_joint_2_shoulder:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_joint_3_elbow:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: true
    max_acceleration: 1.0
  arm_joint_4_wrist:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_gripper_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.05
    has_acceleration_limits: true
    max_acceleration: 0.1
